# Appveyor file
# http://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2013

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

# what combinations to test
environment:
  global:
    nodejs_version: "6"
  matrix:
    - TARGET_ARCH: x64
    - TARGET_ARCH: x86

matrix:
  fast_finish: true

install:
  - C:\WinDDK\7600.16385.1\bin\setenv.bat C:\WinDDK\7600.16385.1\ fre %TARGET_ARCH% WIN7
  - copy redist\winusb\amd64\winusbcoinstaller2* redist\wdf\amd64\
  - copy redist\winusb\x86\winusbcoinstaller2* redist\wdf\x86\
  - cd C:\projects\winusb-driver-generator
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version $env:TARGET_ARCH
  - npm install

build: off

test_script:
  - npm run configure
  - npm run build
  - npm test
  - node test.js
